#!/bin/bash

sudo -v # ask for password only at the beginning

brew update
brew upgrade
brew tap homebrew/versions
brew tap phinze/homebrew-cask

brew install ace \
  android-sdk \
  autoconf \
  automake \
  boost \
  brew-cask \
  cmake \
  freetype \
  git \
  imagemagick \
  ios-sim \
  jpeg \
  libevent \
  libgpg-error \
  libiconv \
  libksba \
  libpng \
  libtool \
  libxml2 \
  libxslt \
  libyaml \
  makedepend \
  mysql \
  node \
  openssl \
  ossp-uuid \
  phantomjs \
  pkg-config \
  postgresql \
  readline \
  redis \
  ssh-copy-id \
  tmux \
  vim \
  wget \
  xz

brew cask install android-file-transfer \
  android-studio \
  appcleaner \
  asepsis \
  caffeine \
  cakebrew \
  calibre \
  chromium \
  clamxav \
  cyberduck \
  dropbox \
  firefox \
  gpgtools \
  imageoptim \
  iterm2 \
  jewelrybox \
  mysqlworkbench \
  perian \
  postgres \
  skype \
  sourcetree \
  spectacle \
  spotifree \
  spotify \
  steam \
  the-unarchiver \
  tinkertool \
  torbrowser \
  transmission \
  vagrant \
  vagrant-manager \
  virtualbox \
  vlc
