#!/bin/bash

sudo -v # ask for password only at the beginning

brew update
brew upgrade
brew tap homebrew/versions
brew tap phinze/homebrew-cask

brew install brew-cask gnupg gsl mysql node openssl phantomjs198 pkg-config readline tree

brew cask install appcleaner caffeine cyberduck disk-inventory-x firefox handbrake imageoptim iterm2 launchcontrol menumeters onyx postgres skype sourcetree spectacle the-unarchiver torbrowser transmission vienna vlc
